# Generated by Django 4.1.2 on 2022-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
